.\"
.\" Copyright (c) 2020 Brian Callahan <bcallah@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd August 14, 2020
.Dt COIN 1
.Os
.Sh NAME
.Nm coin
.Nd command interpreter
.Sh SYNOPSIS
.Nm
.Op Ar file
.Sh DESCRIPTION
The
.Nm
utility is a
.Em command interpreter :
it reads one or more commands, either from the command line of from a
.Ar file ,
and then sets about executing those commands.
It is only capable of understanding commands; there is no scripting language
that
.Nm
understands.
This limits its usefulness as both an interactive shell and for shell script
use.
.Pp
Scripts must be executed as
.Nm Ar file
where
.Ar file
is the name of a script file.
.Nm
does not understand
.Sy ./file
invocation for shell scripts (it will work for binaries).
.Sh AUTHORS
.Nm
was written by
.An Brian Callahan Aq Mt bcallah@openbsd.org .
.Sh BUGS
Lots.
Do not use
.Nm
for any serious work.
